services:
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dare
      POSTGRES_PASSWORD: dare
      POSTGRES_DB: dare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dare -d dare"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Mock of Datasektionen's SSO (and Hive), see
  # https://github.com/datasektionen/nyckeln-under-dorrmattan
  sso:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan:latest
    restart: unless-stopped
    ports:
      - "7003:7003" # sso (OIDC)
      - "7004:7004" # hive
    volumes:
      - ./dev/nyckeln.yaml:/config.yaml:ro

volumes:
  pgdata:
