import type { Lang } from "@/components/landing/countdown"

export const T = {
  sv: {
    presents: "dÅre presenterar",
    tagline: "Hoppa, gör volter, samla Pucko.",
    jump: "Mellanslag: hoppa",
    flip: "Håll i luften: volt",
    jumpTouch: "Tryck: hoppa",
    flipTouch: "Håll i luften: volt",
    land: "Landa på skidorna",
    comboHint: "Volter i rad: kombo",
    start: "Åk!",
    again: "Åk igen",
    orSpace: "eller tryck mellanslag",
    crash: "Vurpa!",
    score: "Poäng",
    cans: "Flaskor",
    metres: "Meter",
    best: "Rekord",
    newBest: "Nytt rekord!",
    flips: ["", "Volt!", "Dubbelvolt!", "Trippelvolt!"],
    manyFlips: (n: number) => `${n}× volt!`,
    perfect: "Perfekt landning",
    bigAir: "Stor luft!",
    hugeAir: "Enorm luft!",
    combo: (n: number) => `Kombo ×${n}`,
    leaderboard: "Topplista",
    back: "Tillbaka",
    empty: "Ingen har åkt än. Bli först!",
    saveTitle: "Spara på topplistan",
    name: "Ditt namn",
    save: "Spara",
    saving: "Sparar…",
    saved: (rank: number) => `Sparat! Du kom på plats ${rank}.`,
    saveFailed: "Kunde inte spara. Försök igen om en stund.",
    checking: "Kontrollerar åket…",
    held: "Sparat! Syns när dÅrestaben kollat det.",
    cantSave: {
      closed: "Topplistan är stängd just nu.",
      rejected: "Åket kunde inte godkännas.",
      offline: "Ingen kontakt med servern, åket sparas inte.",
      blocked: "Du kan inte spara på topplistan.",
    },
    remove: (name: string) => `Ta bort ${name} från topplistan`,
  },
  en: {
    presents: "dÅre presents",
    tagline: "Jump, flip, grab the Pucko.",
    jump: "Space: jump",
    flip: "Hold in the air: flip",
    jumpTouch: "Tap: jump",
    flipTouch: "Hold in the air: flip",
    land: "Land on your skis",
    comboHint: "Flips in a row: combo",
    start: "Ride!",
    again: "Ride again",
    orSpace: "or press space",
    crash: "Wipeout!",
    score: "Score",
    cans: "Bottles",
    metres: "Metres",
    best: "Best",
    newBest: "New best!",
    flips: ["", "Backflip!", "Double backflip!", "Triple backflip!"],
    manyFlips: (n: number) => `${n}× backflip!`,
    perfect: "Perfect landing",
    bigAir: "Big air!",
    hugeAir: "Huge air!",
    combo: (n: number) => `Combo ×${n}`,
    leaderboard: "Leaderboard",
    back: "Back",
    empty: "Nobody has skied yet. Be the first!",
    saveTitle: "Save to the leaderboard",
    name: "Your name",
    save: "Save",
    saving: "Saving…",
    saved: (rank: number) => `Saved! You came in at number ${rank}.`,
    saveFailed: "Couldn't save. Try again in a moment.",
    checking: "Checking your run…",
    held: "Saved! It shows once dÅrestaben has checked it.",
    cantSave: {
      closed: "The leaderboard is closed right now.",
      rejected: "This run couldn't be verified.",
      offline: "No connection, so this run isn't saved.",
      blocked: "You can't save to the leaderboard.",
    },
    remove: (name: string) => `Remove ${name} from the leaderboard`,
  },
} satisfies Record<Lang, unknown>

export type Texts = (typeof T)[Lang]

export const DISPLAY = "font-['Big_Shoulders_Display',sans-serif] font-black"
export const MONO = "font-['IBM_Plex_Mono',monospace] uppercase"
/** Icy letters, like the landing page's countdown digits. */
export const ICE =
  "bg-[linear-gradient(180deg,#ffffff_0%,#eef8ff_26%,#bfe0f8_50%,#f4fbff_57%,#7fb4e4_80%,#b9dcf6_100%)] bg-clip-text text-transparent [filter:drop-shadow(0_0_24px_rgba(150,205,255,.45))_drop-shadow(0_3px_10px_rgba(8,20,60,.45))]"
export const SHADOW = "[text-shadow:0_2px_14px_rgba(5,10,35,.65)]"
