/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as GameRouteImport } from './routes/game'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QrRouteImport } from './routes/qr'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as BattleMetatvRouteImport } from './routes/battle_.metatv'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as AuthedDashboardAdminRouteImport } from './routes/_authed/dashboard/_admin'
import { Route as AuthedDashboardProfilRouteImport } from './routes/_authed/dashboard/profil'
import { Route as ApiAvatarKthidRouteImport } from './routes/api/avatar/$kthid'
import { Route as ApiBattleEventsRouteImport } from './routes/api/battle/events'
import { Route as AuthedDashboardAdminAktivitetRouteImport } from './routes/_authed/dashboard/_admin/aktivitet'
import { Route as AuthedDashboardAdminBattleRouteImport } from './routes/_authed/dashboard/_admin/battle'
import { Route as AuthedDashboardAdminBiljettslappRouteImport } from './routes/_authed/dashboard/_admin/biljettslapp'
import { Route as AuthedDashboardAdminInstallningarRouteImport } from './routes/_authed/dashboard/_admin/installningar'
import { Route as AuthedDashboardAdminPuckopistRouteImport } from './routes/_authed/dashboard/_admin/puckopist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleMetatvRoute = BattleMetatvRouteImport.update({
  id: '/battle_/metatv',
  path: '/battle/metatv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardAdminRoute = AuthedDashboardAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const AuthedDashboardProfilRoute = AuthedDashboardProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthedDashboardRouteRoute,
} as any)
const ApiAvatarKthidRoute = ApiAvatarKthidRouteImport.update({
  id: '/api/avatar/$kthid',
  path: '/api/avatar/$kthid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBattleEventsRoute = ApiBattleEventsRouteImport.update({
  id: '/api/battle/events',
  path: '/api/battle/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardAdminAktivitetRoute =
  AuthedDashboardAdminAktivitetRouteImport.update({
    id: '/aktivitet',
    path: '/aktivitet',
    getParentRoute: () => AuthedDashboardAdminRoute,
  } as any)
const AuthedDashboardAdminBattleRoute =
  AuthedDashboardAdminBattleRouteImport.update({
    id: '/battle',
    path: '/battle',
    getParentRoute: () => AuthedDashboardAdminRoute,
  } as any)
const AuthedDashboardAdminBiljettslappRoute =
  AuthedDashboardAdminBiljettslappRouteImport.update({
    id: '/biljettslapp',
    path: '/biljettslapp',
    getParentRoute: () => AuthedDashboardAdminRoute,
  } as any)
const AuthedDashboardAdminInstallningarRoute =
  AuthedDashboardAdminInstallningarRouteImport.update({
    id: '/installningar',
    path: '/installningar',
    getParentRoute: () => AuthedDashboardAdminRoute,
  } as any)
const AuthedDashboardAdminPuckopistRoute =
  AuthedDashboardAdminPuckopistRouteImport.update({
    id: '/puckopist',
    path: '/puckopist',
    getParentRoute: () => AuthedDashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/battle/metatv': typeof BattleMetatvRoute
  '/dashboard/profil': typeof AuthedDashboardProfilRoute
  '/api/avatar/$kthid': typeof ApiAvatarKthidRoute
  '/api/battle/events': typeof ApiBattleEventsRoute
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/aktivitet': typeof AuthedDashboardAdminAktivitetRoute
  '/dashboard/battle': typeof AuthedDashboardAdminBattleRoute
  '/dashboard/biljettslapp': typeof AuthedDashboardAdminBiljettslappRoute
  '/dashboard/installningar': typeof AuthedDashboardAdminInstallningarRoute
  '/dashboard/puckopist': typeof AuthedDashboardAdminPuckopistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/battle/metatv': typeof BattleMetatvRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/profil': typeof AuthedDashboardProfilRoute
  '/api/avatar/$kthid': typeof ApiAvatarKthidRoute
  '/api/battle/events': typeof ApiBattleEventsRoute
  '/dashboard/aktivitet': typeof AuthedDashboardAdminAktivitetRoute
  '/dashboard/battle': typeof AuthedDashboardAdminBattleRoute
  '/dashboard/biljettslapp': typeof AuthedDashboardAdminBiljettslappRoute
  '/dashboard/installningar': typeof AuthedDashboardAdminInstallningarRoute
  '/dashboard/puckopist': typeof AuthedDashboardAdminPuckopistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/battle': typeof BattleRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/qr': typeof QrRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/battle_/metatv': typeof BattleMetatvRoute
  '/_authed/dashboard/_admin': typeof AuthedDashboardAdminRouteWithChildren
  '/_authed/dashboard/profil': typeof AuthedDashboardProfilRoute
  '/api/avatar/$kthid': typeof ApiAvatarKthidRoute
  '/api/battle/events': typeof ApiBattleEventsRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/_admin/aktivitet': typeof AuthedDashboardAdminAktivitetRoute
  '/_authed/dashboard/_admin/battle': typeof AuthedDashboardAdminBattleRoute
  '/_authed/dashboard/_admin/biljettslapp': typeof AuthedDashboardAdminBiljettslappRoute
  '/_authed/dashboard/_admin/installningar': typeof AuthedDashboardAdminInstallningarRoute
  '/_authed/dashboard/_admin/puckopist': typeof AuthedDashboardAdminPuckopistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/game'
    | '/login'
    | '/qr'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/battle/metatv'
    | '/dashboard/profil'
    | '/api/avatar/$kthid'
    | '/api/battle/events'
    | '/dashboard/'
    | '/dashboard/aktivitet'
    | '/dashboard/battle'
    | '/dashboard/biljettslapp'
    | '/dashboard/installningar'
    | '/dashboard/puckopist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battle'
    | '/game'
    | '/login'
    | '/qr'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/battle/metatv'
    | '/dashboard'
    | '/dashboard/profil'
    | '/api/avatar/$kthid'
    | '/api/battle/events'
    | '/dashboard/aktivitet'
    | '/dashboard/battle'
    | '/dashboard/biljettslapp'
    | '/dashboard/installningar'
    | '/dashboard/puckopist'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/battle'
    | '/game'
    | '/login'
    | '/qr'
    | '/_authed/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/auth/logout'
    | '/battle_/metatv'
    | '/_authed/dashboard/_admin'
    | '/_authed/dashboard/profil'
    | '/api/avatar/$kthid'
    | '/api/battle/events'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/_admin/aktivitet'
    | '/_authed/dashboard/_admin/battle'
    | '/_authed/dashboard/_admin/biljettslapp'
    | '/_authed/dashboard/_admin/installningar'
    | '/_authed/dashboard/_admin/puckopist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  BattleRoute: typeof BattleRoute
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  QrRoute: typeof QrRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  BattleMetatvRoute: typeof BattleMetatvRoute
  ApiAvatarKthidRoute: typeof ApiAvatarKthidRoute
  ApiBattleEventsRoute: typeof ApiBattleEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle_/metatv': {
      id: '/battle_/metatv'
      path: '/battle/metatv'
      fullPath: '/battle/metatv'
      preLoaderRoute: typeof BattleMetatvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/_admin': {
      id: '/_authed/dashboard/_admin'
      path: ''
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardAdminRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/_authed/dashboard/profil': {
      id: '/_authed/dashboard/profil'
      path: '/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof AuthedDashboardProfilRouteImport
      parentRoute: typeof AuthedDashboardRouteRoute
    }
    '/api/avatar/$kthid': {
      id: '/api/avatar/$kthid'
      path: '/api/avatar/$kthid'
      fullPath: '/api/avatar/$kthid'
      preLoaderRoute: typeof ApiAvatarKthidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/battle/events': {
      id: '/api/battle/events'
      path: '/api/battle/events'
      fullPath: '/api/battle/events'
      preLoaderRoute: typeof ApiBattleEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/_admin/aktivitet': {
      id: '/_authed/dashboard/_admin/aktivitet'
      path: '/aktivitet'
      fullPath: '/dashboard/aktivitet'
      preLoaderRoute: typeof AuthedDashboardAdminAktivitetRouteImport
      parentRoute: typeof AuthedDashboardAdminRoute
    }
    '/_authed/dashboard/_admin/battle': {
      id: '/_authed/dashboard/_admin/battle'
      path: '/battle'
      fullPath: '/dashboard/battle'
      preLoaderRoute: typeof AuthedDashboardAdminBattleRouteImport
      parentRoute: typeof AuthedDashboardAdminRoute
    }
    '/_authed/dashboard/_admin/biljettslapp': {
      id: '/_authed/dashboard/_admin/biljettslapp'
      path: '/biljettslapp'
      fullPath: '/dashboard/biljettslapp'
      preLoaderRoute: typeof AuthedDashboardAdminBiljettslappRouteImport
      parentRoute: typeof AuthedDashboardAdminRoute
    }
    '/_authed/dashboard/_admin/installningar': {
      id: '/_authed/dashboard/_admin/installningar'
      path: '/installningar'
      fullPath: '/dashboard/installningar'
      preLoaderRoute: typeof AuthedDashboardAdminInstallningarRouteImport
      parentRoute: typeof AuthedDashboardAdminRoute
    }
    '/_authed/dashboard/_admin/puckopist': {
      id: '/_authed/dashboard/_admin/puckopist'
      path: '/puckopist'
      fullPath: '/dashboard/puckopist'
      preLoaderRoute: typeof AuthedDashboardAdminPuckopistRouteImport
      parentRoute: typeof AuthedDashboardAdminRoute
    }
  }
}

interface AuthedDashboardAdminRouteChildren {
  AuthedDashboardAdminAktivitetRoute: typeof AuthedDashboardAdminAktivitetRoute
  AuthedDashboardAdminBattleRoute: typeof AuthedDashboardAdminBattleRoute
  AuthedDashboardAdminBiljettslappRoute: typeof AuthedDashboardAdminBiljettslappRoute
  AuthedDashboardAdminInstallningarRoute: typeof AuthedDashboardAdminInstallningarRoute
  AuthedDashboardAdminPuckopistRoute: typeof AuthedDashboardAdminPuckopistRoute
}

const AuthedDashboardAdminRouteChildren: AuthedDashboardAdminRouteChildren = {
  AuthedDashboardAdminAktivitetRoute: AuthedDashboardAdminAktivitetRoute,
  AuthedDashboardAdminBattleRoute: AuthedDashboardAdminBattleRoute,
  AuthedDashboardAdminBiljettslappRoute: AuthedDashboardAdminBiljettslappRoute,
  AuthedDashboardAdminInstallningarRoute:
    AuthedDashboardAdminInstallningarRoute,
  AuthedDashboardAdminPuckopistRoute: AuthedDashboardAdminPuckopistRoute,
}

const AuthedDashboardAdminRouteWithChildren =
  AuthedDashboardAdminRoute._addFileChildren(AuthedDashboardAdminRouteChildren)

interface AuthedDashboardRouteRouteChildren {
  AuthedDashboardAdminRoute: typeof AuthedDashboardAdminRouteWithChildren
  AuthedDashboardProfilRoute: typeof AuthedDashboardProfilRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteRouteChildren: AuthedDashboardRouteRouteChildren = {
  AuthedDashboardAdminRoute: AuthedDashboardAdminRouteWithChildren,
  AuthedDashboardProfilRoute: AuthedDashboardProfilRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteRouteWithChildren =
  AuthedDashboardRouteRoute._addFileChildren(AuthedDashboardRouteRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  BattleRoute: BattleRoute,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  QrRoute: QrRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  BattleMetatvRoute: BattleMetatvRoute,
  ApiAvatarKthidRoute: ApiAvatarKthidRoute,
  ApiBattleEventsRoute: ApiBattleEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
